docker-backup:
  image: ogirok/docker-backup
  container_name: docker-backup
  restart: unless-stopped
  volumes:
    - ./backup.py:/backup.py
    - /tmp/backup:/backup
    - /var/run/docker.sock:/var/run/docker.sock
    - ./devctontab:/crontab


